name: Check Repository Owner

on:
  push:
    branches:
      - main

jobs:
  check-owner:
    runs-on: ubuntu-latest

    steps:
      - name: Print repository owner
        run: |
          echo "Repository owner is: ${{ github.repository_owner }}"
